using System;

namespace EulerProblems {
	//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
	//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
	public class Problem2 {
		public int GetSumOfEvenFibonacciNumbersBelowNumber(int max) {
			var previous = 1;
			var current = 1;
			var total = 0;
			while (current < max) {
				var next = current + previous;
				previous = current;
				current = next;
				Console.WriteLine(current);
				if (current%2 == 0 && current < max)
					total += current;
			}
			return total;
		}
	}
}
