using System;
using System.Collections.Generic;
using System.Linq;
using EulerProblems.Helpers;

namespace EulerProblems
{
    //Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
    //Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
    //Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
    //Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
    //It can be verified that T285 = P165 = H143 = 40755.
    //Find the next triangle number that is also pentagonal and hexagonal.
    public class Problem44
    {
        public void GetNextTriPentHexNumber(int start)
        {
            Func<int, int> hex = i => i*(2*i-1);
            Func<int, int> pent = i => i * (3 * i - 1)/2;
            Func<int, int> tri = i => i * (i + 1)/2;

            while (true)
            {
                var hexNumbers = Enumerable.Range(start, start + 100000).Select(hex);
                var pentNumbers = 
            }
        }
    }
}